name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go: ['1.15']

        # Intentionally use specific versions instead of "latest" to
        # make this build reproducible.
        os: ['ubuntu-18.04']

      # Build all variants regardless of failures
      fail-fast: false
    name: ${{ matrix.os }} / Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make get-deps
      - run: make linux-amd64
      - run: make test

      - uses: actions/upload-artifact@v2.2.2
        with:
          name: amazon-ecr-credential-helper
          path: bin/linux-amd64/docker-credential-ecr-login 
